### ISSUE TITLE
Language Button

### ISSUE THREAD

**Issue by EnderHosting** [itsvic-dev/Nova#15]
### Is there an existing suggestion for this?

- [X] I have searched the existing issues before opening this suggestion.

### Describe your suggestion

Add a button (maybe in a corner at the bottom or top) where you can select the languages ​​that exist in the lang configuration (languages) so you can easily change the language / and have it detected depending on the country

### Describe the solution you'd like

Add a language button

**Comment by itsvic-dev** [comment]
Nova doesn't support translations though, at least not natively
