### ISSUE TITLE
"view as admin" still shown on server pages which are errors (ex. server doesn't exist) and goes to /servers/view/undefined

### ISSUE THREAD

**Issue by am5z** [itsvic-dev/Nova#22]
### Nova version

v1.2.0

### Observed behavior

title

### Expected behavior

shouldnt show view as admin

### Steps to reproduce

title

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by itsvic-dev** [comment]
Fixed in Nova 1.3.0.
![image](https://github.com/user-attachments/assets/74065f62-994d-4787-aed2-708bb1c42c39)
