### ISSUE TITLE
Ability to normalize cpu

### ISSUE THREAD

**Issue by 0x7d8** [itsvic-dev/Nova#27]
### Is there an existing suggestion for this?

- [X] I have searched the existing issues before opening this suggestion.

### Describe your suggestion

A toggle to make cpu limits be normalized to 100%, eg 100% usage on 400% turns into 25%/100% and when you hover over it, it shows the original stats

### Describe the solution you'd like

A toggle to make cpu limits be normalized to 100%, eg 100% usage on 400% turns into 25%/100% and when you hover over it, it shows the original stats

### Additional context

im held hostage by vic now

**Comment by amogusreal69** [comment]
> im held hostage by vic now
do you need help
