### ISSUE TITLE
Avatar Upload

### ISSUE THREAD

**Issue by theMackabu** [itsvic-dev/Nova#3]
### Is there an existing suggestion for this?

- [X] I have searched the existing issues before opening this suggestion.

### Describe your suggestion

The ability to upload an avatar for a user.

### Describe the solution you'd like

User settings: upload/remove avatar
Admin panel: ability to remove avatars/prevent user from using custom avatars

**Comment by itsvic-dev** [comment]
Implemented in Nova 1.2.0.
