### ISSUE TITLE
per game banner

### ISSUE THREAD

**Issue by ThunderNodes** [itsvic-dev/Nova#5]
### Is there an existing suggestion for this?

- [X] I have searched the existing issues before opening this suggestion.

### Describe your suggestion

So, I suggest implementing a per-game banner to enhance the panel theme, making it more solid and visually appealing. If you add this update to the Nova theme, it would be great, and panel admins could choose a per-game banner for the server.

### Describe the solution you'd like

When that is implemented, you can control the per-game banner on Nova Studio and upload your own game banner.

**Comment by itsvic-dev** [comment]
closing in favor of #6
