### ISSUE TITLE
Personal Background for main page and every egg.

### ISSUE THREAD

**Issue by Logiceb** [itsvic-dev/Nova#6]
### Is there an existing suggestion for this?

- [X] I have searched the existing issues before opening this suggestion.

### Describe your suggestion

**I suggest adding a custom background to the home page of the panel as well as having it for each egg separately.**

![image](https://github.com/itsvic-dev/Nova/assets/140463780/f5f2a70a-2983-48c2-8a38-e1501662b0cf)

### Describe the solution you'd like

I imagine it to have an option from which we can change the background for the main page and to be able to add for each individual egg a new section in which to write, for example, nestid or eggid and the photo and to show this photo only to egg/nest we set to.

**Comment by itsvic-dev** [comment]
Implemented in Nova 1.2.0.
